FORMAT: 1A
HOST: http://test.datatile.eu

# DATATILE Dashboard draft

## Dashboard [/api/v2/dashboards/{hash}]

+ Parameters
    + hash (string) - hash of a existing dashboard

### Get a dashboard [GET]


+ Response 200 (application/json)
   
        {
            "available": true,
            "projects": [
                {name: "projects for controls", hash: "9586244ef7ed408fbe44c65eedf67e40"}
                {name: "crisis!", hash: "a2e459ff9a554b15b6aa1b2c6ae45621"}
            ]
        }